### ISSUE TITLE
Suggestion: Input Map Replays

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#424]
Hey, there. So, I was thinking that input map replays would be a cool feature to add. Some games have an attract mode / demo mode, where the game plays itself while you watch. Other games have special powers or abilities that similarly hinge on replays (think of the "Clone" weapons from the Megaman games, or the time traveling recording mechanics of games like Braid). Cinematics can also be the product of replays, theoretically (the developer creates the cinematic by moving the characters around one by one, for example).

Adding replaying capabilities to the input maps would allow this to be done, and it should keep the actual replay data relatively simple - rather than a video, for example, the data would just be the names of the inputs being pressed.

The idea is to keep it simple with just a few functions, at least initially. 

`startRecording()` - Begins recording the specified replay data. This doesn't advance the recording process - the developer does this using the `frame()` function below.

`stopRecording()` - Stops recording the specified replay data.

`frame(int frameNum)` - Sets the frame for the replay data. This function alone should allow for various effects should the developer so choose, such as playing, stopping, speeding up replay input sequences, or slowing them down. When recording, this function seeks the recording and allows the developer to record inputs. When not recording, this function plays back the inputs that are stored within the recording.

`frame()` - Returns the current frame number.

`load()` - Loads recording data to be played or saved. Either an array of arrays of Strings (inputs) can be provided, or a file name can be provided.

`save(String replayDataName, String outputFileName)` - Saves the specified recording data to a text file.

`currentInputs(int frameNumber)` - Returns an ArrayList of the currently pressed inputs for the specified frame. If no frame number is given, it defaults to the current frame.

`on(Boolean on)` - Whether the replays are actively pushing inputs (on), or if the replay's just going through the process without affecting controls (off).

`ignore - ArrayList<String>` - Allows you to set certain inputs to be ignored.

I don't think this would support inputs with more finesse, like analog sticks or pressure-sensitive triggers, but it'll get the job done for simple "on-off" controls. In the future, this might be able to be expanded to have a "deep copy" mode that will allow it to work with actual clones of inputs for maximum accuracy at the cost of increased memory usage.

To facilitate replays, some sort of `push()` function that would allow you to push a result to an input in the InputMap will most likely need to be added so that the replays can push inputs when they're played back.

I suppose a Replay would be a class instance, not a static class that works off of bdx directly, for example.

**Comment by GoranM** [comment]
> Some games have an attract mode / demo mode, where the game plays itself while you watch. Other games have special powers or abilities that similarly hinge on replays (think of the "Clone" weapons from the Megaman games, or the time traveling recording mechanics of games like Braid).

I'm not that familiar with Megaman games, so I'm not sure what you mean by "Clone weapons". However, I know for a fact that Braid's time travel mechanic is implemented via full game state snapshots, and I suspect that many games offering a "demo mode" use the same approach, because unless your game state is completely deterministic, based solely on user input, replaying input alone is highly unlikely to work as expected.

**Comment by SolarLune** [comment]
I have no idea what you mean - I'm pretty sure no attract mode or demo mode used full game snapshots. Why would they? The only reason you would need that is, like you said, if the demo game and level is non-deterministic. However, it seems like almost no average game would need to have random elements in it, and if so, they could be manipulated and controlled via seeds. It seems like, especially for arcade games, the layouts of pretty much everything in the game was programmed and placed into specific positions, so there was no "random" elements.

It feels like most games would just load up the demo level, play the demo inputs, and let the attract mode play out. Enemies that, for example, switch behavior due to being attracted to the player being too close, or that are defeated by the player would always have that happen, since they're always spawned in the same place and the player always moves and attacks in the same way. The only way this would be "trumped" is if you had actually random numbers mess with their timing, placement, attack levels, etc.

I'd think Attract modes were popular long before games even had the excess memory accessible to manage full game states for every second of every item and weapon in a gameplay snapshot of, say, 1:00. 

______________

By "clone weapons", I meant the weapons that created clones of your character as you moved around and attacked. I can't think of any other games that had similar mechanics, but it's a fairly simple and "usual" weapon.

Also, you're correct that a game like Braid in which you had control over the entire game wouldn't use control-based replays, though; my mistake.

**Comment by GoranM** [comment]
I'm not talking about old arcade games - Your mention of "Braid" kinda made me think that we're discussing this in a relatively modern context, where even simple simulations (like retro knock-offs) rely on more involved systems that may not be completely deterministic.

For BDX, specifically: We depend on Bullet, and I've witnessed an identical scene diverge on two different machines (the outcome of the physics simulation was different, even when the initial conditions were exactly the same). I'm not sure if that's a 32bit vs 64bit issue, or something else that could make the floating point math come out a bit different, but it doesn't appear to be reliably deterministic.

Putting those potential issues aside: I'm not sure if "input record and replay" belongs in the engine, because it doesn't seem to have sufficiently general utility. It's helpful if you want to make a "demo mode" (assuming your game is truly deterministic, of course), but not much beyond that (or so it seems).

Can you think of any other use cases?

> By "clone weapons", I meant the weapons that created clones of your character as you moved around and attacked. I can't think of any other games that had similar mechanics, but it's a fairly simple and "usual" weapon.

Well, I still don't really understand what you mean. Is it like a gun that shoots bullets which spawn clones, or a device that creates a clone in place, or something else? Do the clones just follow what you do instantly, or is there a delay?

**Comment by SolarLune** [comment]
> For BDX, specifically: We depend on Bullet, and I've witnessed an identical scene diverge on two different machines (the outcome of the physics simulation was different, even when the initial conditions were exactly the same). I'm not sure if that's a 32bit vs 64bit issue, or something else that could make the floating point math come out a bit different, but it doesn't appear to be reliably deterministic.

That seems like a pretty large problem, as that means that puzzle games (think The Incredible Machine where you place objects to solve puzzles) may not work reliably. As far as I understand it, a physics simulation should be 100% deterministic and predictable, regardless of accuracy. This should especially be the case for BDX since it seems like the physics simulation is rather simply approached (i.e. it just steps through it without regard for sub-steps or target frame-rate or anything like that).

> Your mention of "Braid" kinda made me think that we're discussing this in a relatively modern context, where even simple simulations (like retro knock-offs) rely on more involved systems that may not be completely deterministic.

Such as? What involved systems may not be completely deterministic? It would seem to me that a game will be completely deterministic unless the developer adds an outside, non-seeded random influence that actually impacts gameplay (not just something like particle effects or screen shake or something).

> Can you think of any other use cases?

It seems like any general replay functionality could work with this. If you have, for example, a soccer game where the player inputs different actions to move the players around the field and score a goal, recording those inputs should be enough to enact the same scene back again. That way, you could make recordings / replays that could be played back in-game.

To my knowledge, Super Smash Bros. Wii U actually does replays this way - it records the button presses of the players and the stage conditions, sets everything up, and plays it out. It's not a video, as you can pause and rotate the game scene. It doesn't save the state of each object and player in play constantly - just the inputs. You can actually throw off the replay in some cases. [See the wiki entry under Data.](http://www.ssbwiki.com/Replay)

This is why each update that rebalances the game can make some replays incompatible - the core game balance changed, so the matches can't be reconstructed the same way as they initially occurred.

> Well, I still don't really understand what you mean. Is it like a gun that shoots bullets which spawn clones, or a device that creates a clone in place, or something else? Do the clones just follow what you do instantly, or is there a delay?

The weapon spawns clones that follow your movements from awhile ago, if I recall. It's a pretty specific power, though, so you're right that it's not a generic gameplay element. It's something that a developer could work on themselves.

**Comment by GoranM** [comment]
> As far as I understand it, a physics simulation should be 100% deterministic and predictable, regardless of accuracy. This should especially be the case for BDX since it seems like the physics simulation is rather simply approached (i.e. it just steps through it without regard for sub-steps or target frame-rate or anything like that).

I thought so too, but then I witnessed the aforementioned inconsistency, and now I don't know what to believe.

> Such as? What involved systems may not be completely deterministic?

Anything that relies on a highly complicated system that may not be completely deterministic, like a physics engine, *I suspect* (as I said).

Of course, I don't know for sure, but I know that recording state snapshots, with a basic compression scheme, is essentially guaranteed to work, and I would assume that most developers would prefer the stability of that approach, instead of having to potentially deal with heisenbugs like these:

> Replays of Wi-Fi matches are more likely to desync than local matches due to the frequent lag experienced in games, __but local replays can also be subject to the problem. The cause of "desyncs" is unknown__, though it is speculated it has to do with save data of replays becoming corrupted by some outside factor. In addition, __it is possible for a replay that plays fine to randomly desynchronize when played again, and after some tries, play correctly again.__

Did you actually build and test this system already? If not, I would suggest you do that first.

If it works well enough, and we can confirm that on our systems (more or less), then I think it would be worthwhile.

**Comment by SolarLune** [comment]
OK, so I completed my first go at this. I still have to test it with a ton of objects running the same recording to see if they desynchronize for some reason, but at least it works for now. Test if you guys want - the API is pretty simple compared to my first post.

```java
Replay replay = new Replay();  // Create a new replay

replay.recording = true;  // Turn on recording input key presses

replay.frame(replay.frame() + 1);  // Advance the recording

// And when you want to play it back, do the same thing, but with recording off

replay.recording = false;

replay.frame(replay.frame() + 1);  // Playback the recording
```

I think I'd prefer dedicated `record()` and `play()` functions compared to the `frame()` approach, so that might be something I change.

Here's the branch: https://github.com/SolarLune/bdx/tree/Replays

Note that I added the ability to force inputs going to specified input map names, but I had to do it on a per-input-type basis (i.e. one function for pressed, one for down, and one for released) as there's no way to ensure the push() function would properly release the input once it's no longer being called (?). I guess I could build it into the input processors, but that'd be a lot of work just for input map replays, I dunno.

**Comment by GoranM** [comment]
I've made a small test demo: [imap_logger.blend](https://www.dropbox.com/s/i9vau4pk4d1m4st/imap_logger.blend?dl=1)

It starts recording when you start the game. Spawn some Spheres with S, and run through them with Sacky (you can control him with the arrow keys). When you want to stat replay, hit Enter.

Maybe I did something wrong, but on my system, it doesn't seem to work - There is an almost immediate desync, and I get a completely different end state from the one that was previously recorded.

**Comment by SolarLune** [comment]
Hey, thanks for the test. 

I get similar results to you that the end result of the simulation is different each time. After looking it over, it would appear that nullifying the velocity of Sacky when we reset and playback might be part of the problem that could be slightly throwing things off, but it also might indeed be the physics engine. Nullifying the velocity before replay helps to make things slightly more consistent, but it still deviates more than it should.

It seems like the physics engine may not be deterministic, like you said. Something [this Gamasutra article](http://www.gamasutra.com/view/feature/2029/developing_your_own_replay_system.php) mentions is that 2 20 ms physics steps are not the same as 1 40 ms physics step, so some way to ensure that we run the physics in a flat, predictable way would probably be our best approach. It should be doing that now, though, right?

I guess the alternative, assuming this doesn't work / is too complex, might be to attempt to make Replays fully state-based, like you suggest.

For now, I might try to refine the replay function a bit and perhaps do another test in mid-air to see if it's the physics engine resolving collisions that's the problem.

**Comment by SolarLune** [comment]
OK, so according to this Bullet Wiki page:

http://www.bulletphysics.org/mediawiki-1.5.8/index.php/Stepping_The_World

Using maxSubsteps = 0 means that the engine can't act in a deterministic manner. So I guess that's the core problem here.

I tried messing around a bit with it, but didn't notice determinism, so I'll have to try again later today when I have more time.

**Comment by GoranM** [comment]
> It should be doing that now, though, right?

Yes. As you can see in the code, we run at a fixed time step.

> Using maxSubsteps = 0 means that the engine can't act in a deterministic manner. So I guess that's the core problem here.

I don't know who wrote that, but I think they're assuming that you're passing in a varying timeStep (actual time since last frame) to stepSimulation, in which case, yes, that would be "the death of determinism". However, we're always stepping by TICK_TIME, which is a constant 1f/60f, so that should not be an issue.

I ran a few more tests, and I think I found a bug: If you use `im.down("reset_and_playback")`, instead of `im.hit(...)`, to spawn multiple spheres while holding down Enter, the replay of that will result in a different number of spawned spheres - one less than was spawned originally.

Looks like "down" is returning false one frame before it should.

Bullet seems to be deterministic, but only if you're starting with a freshly created world. I confirmed this by spawning a few spheres in init:

```java
for (int i = 0; i < 4; ++i){
    scene.add("Sphere").position(bounds.position());
}
```

Waiting until they came to rest, and then calling `scene.restart()` - The simulation after the restart was identical to the one before the restart.

I would move Replay into InputMaps, as an internal class. Instead of Replay, call it Logger, because that makes sense in that context, and then make a single instance on InputMaps, so it can be accessed in-game like: `Bdx.imaps.logger`. That way, you can preserve your data across scene restarts.

With that, and with the aforementioned bug fixed, it should work, in theory.

Beyond that, we would need to test replay data recorded on one machine, by playing it back on the other - I suspect we will have [some issues](http://www.gamedev.net/topic/567626-deterministic-physics-replay/#entry4631147) there, but it might be "good enough" to actually include in the engine.

> I guess the alternative, assuming this doesn't work / is too complex, might be to attempt to make Replays fully state-based, like you suggest.

While that would be more reliable, it's still not that easy to implement, especially when it has to be a general solution.

**Comment by SolarLune** [comment]
> im.hit(...), to spawn multiple spheres while holding down S, the replay of that will result in a different number of spawned spheres - one less than was spawned originally.

Oddly, I didn't get that error - it always gave me the correct number of spheres. Maybe I corrected the bug after you tested it without knowing.

> Bullet seems to be deterministic, but only if you're starting with a freshly created world. 

Maybe so. I tested out recording and playing back after restarting the scene, and I think I was able to get reliably the same results throughout. So it might be worth a shot after all.

________________

OK, I took your advice and changed it - the Replay class is now a single instance in the Bdx.imaps instance, and is called `logger`. I remade the API to be a bit simpler. Calling record() records, and calling play() plays. There's no more frame() function; you just adjust the currentFrame property if you want to change it. The record() and play() functions increment the currentFrame property automatically. There's a save() function to save a replay using JSON (goes to the user directory), which seems to work, but I can't get the load() function to work with a replay file - I get an error that says 
```
Exception in thread "LWJGL Application" java.lang.ClassCastException: com.badlogic.gdx.utils.Array cannot be cast to java.util.ArrayList
```

So I dunno - maybe I did something wrong.

Here's the test blend file, adjusted to work with the new API. I also removed the textures from the blend file because I didn't have them in the project folder I put them in, and BDX wouldn't start without them, even though those textures were packed.

https://app.box.com/s/vqqghnhhiqjlou35ldfv3gdglyfnguyf

Controls are the same; you can press R to restart the scene, C to delete the recording, and O and P to save and load (though, again, loading's broken).

_________

As for the state-based approach, it might be possible to do with basic position, scale, and orientation saves and a facility to store user-designated parameters, though it's not ideal, for sure.

**Comment by GoranM** [comment]
> Oddly, I didn't get that error - it always gave me the correct number of spheres. Maybe I corrected the bug after you tested it without knowing.

Are you sure you ran the test as I described?:

> __If you use im.down("reset_and_playback"), *instead of* im.hit(...)__, to spawn multiple spheres while holding down S, the replay of that will result in a different number of spawned spheres - one less than was spawned originally.

The bug is still present in your latest changes:

```java
			if (Bdx.imaps.hit(input)) // <-- when this is true
				recordedInputs.add(input + "_hit");
			else if (Bdx.imaps.down(input)) // <-- so is this
				recordedInputs.add(input + "_down");
			else if (Bdx.imaps.up(input))
				recordedInputs.add(input + "_up");
```

When an input is "hit", it is also "down", but your code is not logging that "down".

> I think I was able to get reliably the same results throughout.

Given that the logging bug exists, I don't see how it would be possible to get "reliably the same results throughout".

Even with the logging bug fixed, there is still an issue with scene restart, where the scene is initialized a bit too late (relative to original game state). That issue can be resolved by moving the requestedRestart block to the top of the Scene.runObjectLogic method, and with that done, things finally seem to work properly.

> There's a save() function to save a replay using JSON (goes to the user directory), which seems to work, but I can't get the load() function to work with a replay file - I get an error that says
>
>`Exception in thread "LWJGL Application" java.lang.ClassCastException: com.badlogic.gdx.utils.Array cannot be cast to java.util.ArrayList`
>
> So I dunno - maybe I did something wrong.

Well, reading the documentation:

> Class names are only output when they are required for deserialization. If the field was ArrayList<PhoneNumber> numbers then class names would only appear when an item in the list extends PhoneNumber.

Since Logger is concretely `ArrayList<ArrayList<String>>`, I would expect the following to just work:

```java
// save
Json json = new Json();
String text = json.toJson(im.logger);
// load
im.logger = json.fromJson(InputMaps.Logger.class, text);
```

However, looking at the error, it seems like it assumes that you're using the libgdx Array, instead of ArrayList. I don't think it's supposed to do that, so it might be a bug.

You should probably ask this question in the libgdx community (their forums, I suppose) - someone there should be able to clarify this.

In the meantime, I guess you can just use their Array, since that's what the deserializer assumes, so that would probably work.

> Here's the test blend file, adjusted to work with the new API.

I can't download the .blend - I get a 404. Do you have a dropbox account?

> I also removed the textures from the blend file because I didn't have them in the project folder I put them in, and BDX wouldn't start without them, even though those textures were packed.

There was no need for you to manually "put" textures anywhere. When you unpacked my .blend, and went on to create a project from that, you should have been able to do your work in that project, and then create a packed .blend from that.

This could be a bug in the project packing/unpacking code ... Could you elaborate a bit on what you did, exactly?

**Comment by SolarLune** [comment]
> Are you sure you ran the test as I described?:

No, sorry, I guess I misunderstood you. However, I don't think that description is correct. You can't use that binding to spawn spheres, unless you mean to make it spawn spheres, not just make it so that it runs when you hold down Enter...? So I'm not sure what you mean.

> When an input is "hit", it is also "down", but your code is not logging that "down".

> That issue can be resolved by moving the requestedRestart block to the top of the Scene.runObjectLogic method, and with that done, things finally seem to work properly.

Thanks, fixed both issues.

> Given that the logging bug exists, I don't see how it would be possible to get "reliably the same results throughout".

Well, I was able to get reliable, consistent results between simulations by restarting the scene before playing the logger.

> In the meantime, I guess you can just use their Array, since that's what the deserializer assumes, so that would probably work.

Yeah, I asked and the solutions were to register something with the deserializer, or just use Arrays. I thought it'd be a simpler solution to just base the logger off of Badlogic Arrays instead, so that's what I did. Now loading should work fine - thanks.

> I can't download the .blend - I get a 404. Do you have a dropbox account?

Yeah, here it is on Dropbox.

https://www.dropbox.com/s/7k24u1nqozqy8jy/imap_logger2.blend?dl=0

I've included a replay file (replay.txt) in the blend file. Just save it to your user directory (if you save a replay, it'll go there as well in the demo). Once you've done that, you should be able to load the replay by pressing the P key when the game's running. On pressing Enter to run the replay, the square should move left, move right, and double-jump over two spheres. After a short period of time, the top sphere falls off of the bottom one, and that's it.

> There was no need for you to manually "put" textures anywhere. When you unpacked my .blend, and went on to create a project from that, you should have been able to do your work in that project, and then create a packed .blend from that.

Ah, that was the issue. I didn't unpack it and create a new project for it, I just stuck it into an existing project (in which I had already deleted the textures).

If it all looks good, then the PR's been submitted.

**Comment by GoranM** [comment]
> You can't use that binding to spawn spheres

I used the wrong mapping name - It should have been "spawn_sphere", as the context implies.

> I was able to get reliable, consistent results between simulations by restarting the scene before playing the logger.

For your recording tests, did you simply move Sacky around for a short time, without colliding with anything else?

> the square should move left, move right, and double-jump over two spheres. After a short period of time, the top sphere falls off of the bottom one, and that's it.

The test should be more involved: Spawn 12 Spheres, and use Sacky to move them into the corners of the stage (3 to each corner).

I need a screenshot of the final state (when all bodies have come to rest in their final positions) to confirm that I'm getting the same thing.

> Ah, that was the issue. I didn't unpack it and create a new project for it, I just stuck it into an existing project (in which I had already deleted the textures).

Your .blend is still missing textures ...

Start from my .blend, as a base. Packing that should work fine.

Also, I would appreciate it if you could generally clean up the demo, by removing unnecessary code.

**Comment by SolarLune** [comment]
I started to get the demo together, but the physics weren't replaying correctly - I couldn't get the spheres to go where I originally placed them. Sacky's movements were also off. I tweaked the friction on the materials, which might account for the difference, but I'd think it would play through the same way nonetheless, so I dunno.

It would appear that the only real alternative is to go with fully state-based replays, which is unfortunate. I guess the idea for that would be to just store Position, Scale, and Rotation, creation and end events, and provide an API where you can store custom variables. Not sure if a HashMap of <String, Object> would work  - I don't remember if casting to and from Object works OK. 

I guess the alternative to that casting would be to either work with JSon (since it can handle more types), or just make it a String, String hashmap and let the developer convert from whatever actual value to a string and back. Storing entire clones of components would be way too much, I think.

**Comment by GoranM** [comment]
I tested https://github.com/SolarLune/bdx/commit/d1c65825130d40f6767f762ed61916e0a45f1c3e with this demo: [imap_logger3.blend](https://www.dropbox.com/s/2lq19ci4hg20rm4/imap_logger3.blend?dl=1).

It appears to work correctly on my machine.

Make sure that your HEAD is on the proper commit, and that BDX was recompiled. Also, unless your core/libs is a symbolic link to libs in the github repo, you'll need to recreate the demo project.

**Comment by SolarLune** [comment]
OK, your demo worked, while my attempts didn't. I can only guess by triggering playback on different frames, Sacky was in slightly different positions, and that's what messed with it? So things have to be in exactly the same position and times for it to work. I dunno, but that sounds like a solid enough theory.

In any case, I think I have it working. Here's a slightly altered test file with the ability to save and load added. There's also a replay that you can copy and paste or save out to the replay.txt file in your user directory to test.

Pushing around 12 spheres takes too long - here's a small, simple test where I herded three spheres into the top-right corner of the playfield. The result should look like this:

![inputmapreplayresult](https://cloud.githubusercontent.com/assets/4733521/9702438/c32c54e2-5411-11e5-892f-26c8e31a70a4.png)

Here's the test file:

https://www.dropbox.com/s/cl4yk5s5eayb7mu/imap_logger3.blend?dl=0

If this works for you, the last thing I'll do is just swap out the long string name for a simpler one when JSON'd for smaller replays and then submit a PR, I guess.

**Comment by SolarLune** [comment]
Whoops, the replay.txt file wasn't correct - here's a corrected version.

Test file:

https://www.dropbox.com/s/cl4yk5s5eayb7mu/imap_logger3.blend?dl=0

Result:

![inputmapreplayresult](https://cloud.githubusercontent.com/assets/4733521/9702459/09497076-5413-11e5-9df1-1334422e5c48.png)

Once everything stop's moving, the replay should basically be finished.

**Comment by rafcolson** [comment]
I got accurate results, even with seven spheres. But what's not clear to me is where ```replays.txt``` is saved. After doing my own tests I couldn't replace your test with mine anymore, so I couldn't actually confirm that your test has accurate results.

**Comment by SolarLune** [comment]
^ replay.txt is saved in the user directory (for Windows, it's C:/users/--username--). I'd like for it to be elsewhere, myself. I'm using a LibGDX file-handling function for saving the file out, and it saves to the user-directory. There are other functions as well, though.

Thanks for testing it out!

**Comment by rafcolson** [comment]
Thanks. I found it now. Tested your replay and it's exactly the same result.

**Comment by SolarLune** [comment]
Cool! The PR I submitted has been updated - now String classes are just represented by "String" in the replays, which should lessen the size a bit. 

It depends on the size of the replay, but I think for most games, you'd be able to record for a lot of time before the replay becomes large. The demo replay averages to less than 1 KB per second, I think, so that'd be around 3.6 MB for an hour-long replay (which is absurdly long). 

Of course, there's a ton of dead space in the current replay - most replays would probably have constant play without "down-time", so this isn't indicative of real-world usage. However, even if it were 10 times as much in real world usage, that's still only 36 MB for an hour-long replay, which is still great, and most people wouldn't play for an hour (or watch a replay for an hour), so it all works out.

**Comment by rafcolson** [comment]
I think this is an ideal solution for running demos of various levels when you start the game. And of course also for narrative-like scenes between levels. I will personally will make use of this for sure. (if I ever come that far finishing a project).

**Comment by GoranM** [comment]
> Pushing around 12 spheres takes too long

Small inconsistencies can cause errors that only become obvious after interacting with more than just a few objects, for more than a few seconds.

Please run the test as I described - It shouldn't take you more than a minute.

**Comment by SolarLune** [comment]
OK, I think I got it.

Here's the finished outcome.

![finishedscene](https://cloud.githubusercontent.com/assets/4733521/9835601/cdf37efa-59a7-11e5-84ba-9a626204bb35.png)

Here's the replay file.

https://www.dropbox.com/s/eysjme1h0ldrppc/replay.txt?dl=0

The next question is "how do we stop the game from taking input for bindings while a replay is playing"? Also, we need to lock certain bindings so they're not recorded (i.e. you probably wouldn't want the logger to record a pause button).

**Comment by GoranM** [comment]
It seems to work perfectly.

> how do we stop the game from taking input for bindings while a replay is playing

For now, you can just have something like `imaps.userInputEnabled`, which the user could set to false if required.

> we need to lock certain bindings so they're not recorded (i.e. you probably wouldn't want the logger to record a pause button).

Actually, I would want to record everything, because I would want the replay to be authentic.

**Comment by SolarLune** [comment]
> For now, you can just have something like imaps.userInputEnabled, which the user could set to false if required.

That won't be acceptable, as the user would most likely want to take special inputs to stop the playback (like Start / Pause, which would be part of the input map). I think we would need a way to "lock" individual inputs from being recognized - perhaps an API like:

```java
Bdx.imaps.get("jump").lock(0); // Locks it from accepting input, no matter what (all inputs)
Bdx.imaps.get("jump").lock(1); // Locks it from accepting natural inputs (the player)
Bdx.imaps.get("jump").lock(2); // Locks it from accepting forced inputs (the replay)

Bdx.imaps.get("run").unlock();  // Unlocks it
Bdx.imaps.lock()  // Locks all inputs
Bdx.imaps.unlock()  // Unlocks all inputs
```

With those two sets of functions, you can lock all of the inputs except the ones that you actually want to receive.

> Actually, I would want to record everything, because I would want the replay to be authentic.

I'd personally probably want the pause button to trigger the replay menu, so recording and playing it back mid-replay could exit the replay, and so wouldn't work.

However, I don't think it's worth the extra work and code to add an ability to omit recording inputs if we just add the ability to lock inputs (it would seem that you can just force-lock the pause button to prevent it from going off in replay).

**Comment by GoranM** [comment]
> That won't be acceptable, as the user would most likely want to take special inputs to stop the playback (like Start / Pause, which would be part of the input map).

Replay control seems like one of those special things where referencing an input directly would be acceptable, and that would work because the replay system is only aware inputs that are mapped.

But, if you want absolutely everything to go through imaps, then you would need something like the locking mechanism you describe, which seems fine (strings may be more descriptive than integers, but if you like that better, I'm ok with it).

**Comment by SolarLune** [comment]
I think about this sometimes, but I'm thinking this just doesn't need to be a core part of the engine. Not every game will have an attract mode or use replays - not even a lot of them will. I think it's best not to clog up the engine with something that most developers won't use; that's kind of the appeal of BDX.

Perhaps I'll add this to my own set of solutions / module for open-source BDX game development, but I think it best to forego this for core BDX. What do you guys think? 

If we drop it, could we push out another release of BDX soon?

**Comment by rafcolson** [comment]
I can't really say what I think about it. This feature will probably be not be used as much as others, but the same could be said of some other features too. For example, ```GameObject.updateJoinedMesh()``` probably won't ever be used by those who are not developing for mobile devices (on Android and such). These are specific features, for specific needs, but useful nonetheless. Putting it on your own module would be good too. Maybe we could have a separate page in the API on which external modules are introduced and referenced. This way it could still add value to Goran's BDX, but externally. I was thinking to eventually do the same thing with some other special features I'm creating. It could be titled "External modules for BDX". Just a thought.

**Comment by GoranM** [comment]
Being able to record a game, and play it back, is a fairly general feature (it's not tied to just a single game type), so I think it should be in the engine.

The PR is already there, and it works, so it doesn't really make sense to drop it at this point.

**Comment by SolarLune** [comment]
OK, I'm pushing on with it as best as I can, then.

I've updated the PR. Changes:

> It might be worth the effort to optimize a bit, by making Logger extend HashMap instead of Array, and storing only frames that have some active inputs, so we don't have to store a bunch of [] entries.

Done. It's now extending a HashMap and works by storing the keys pressed, held, or released for just the current frame. To make this possible, I added a maxFrame variable that indicates the length of the replay, as the size of the HashMap doesn't indicate how many frames it contains for replay.

> Make it store and load plain json. I think you can do that via setElementType as they demonstrate on their wiki.

Tried to get it to save data simpler, but I couldn't quite make out how to make it store strings as standard strings, rather than instances of the String class with the value of the text itself. It's roundabout and unnecessary.

I wanted to add a locking mechanic, but it was pretty complex as I started writing it, so I decided to ditch that in favor of a remapping function to do more, overall. Now you can remap a saved replay to change what keys were pressed. If you remap an input to point to a blank string (""), then it will be ignored when it's replayed.

**Comment by SolarLune** [comment]
Oh, cool! So this was merged.

Does this mean we'll get a new release of BDX?

**Comment by GoranM** [comment]
If you want, sure.

It's up: tps://github.com/GoranM/bdx/releases/tag/v0.2.0

**Comment by SolarLune** [comment]
Thanks a ton! I'll close this now. What a ride, haha!
