### ISSUE TITLE
Memory Leak

### ISSUE THREAD

**Issue by SolarLune** [GoranM/bdx#476]
Hey, there. So, there appears to be a memory leak in BDX currently if you restart the scene. 

It seems(?) OK for the first few restarts, but as you keep triggering a restart, the memory allocation rises and stops coming back down. 

Maybe we're not disposing stuff we should be? AFAIK, we don't have to worry about ShaderPrograms tied to Shaders (in the matShaders list that have valid, used materials and that the ShaderProvider will provide shaders for), as the Provider will handle disposal of those programs. I am disposing the filters in the scene, though.

**Comment by GoranM** [comment]
> Maybe we're not disposing stuff we should be?

It's possible. You can look through all the disposable libgdx objects that we create on scene initialization - if any of them are not disposed when the scene is restarted, that's probably the cause.

You can also try running your game without shaders/filters - If that minimizes growth, it would imply a disposal issue with those resources.

PS: I just searched through the repo for "dispose(", and I don't see Scene.dispose being called anywhere ...

**Comment by rafcolson** [comment]
@SolarLune 

Do you compare percents in the Windows Task Manager to see the rising? Or is there another kind of tool that can be used (on Windows) ?

**Comment by SolarLune** [comment]
@rafcolson - I use the Task Manager. The RAM usage for each program can be seen as individual amounts, and it definitely rises over time - it got up to around a Gigabyte with enough restarts, if I recall.

It looks like I forgot to dispose the framebuffers on resize - thanks to @caresilabs for the fix!

@GoranM - After this gets merged in, I'll look to see if the leak is solved. If so, a new release would probably be a good idea. The shader fixes would also be in that new release; without those, custom shaders didn't work without crashing BDX, I think, haha.

**Comment by GoranM** [comment]
> After this gets merged in, I'll look to see if the leak is solved.

You can fetch and subsequently checkout any BDX branch on github, so you don't have to wait for me to merge it into master.

I merged the referenced PR, because it seems to address an existing leak, but unless you're re-sizing the window after every scene restart, I think the issue I mentioned in my previous post is more likely to be at the root of the problem (for your case, at least).

**Comment by SolarLune** [comment]
Well, I added a couple of lines that are some things that we did need to do, but they didn't resolve the issue completely. You guys can check the memory usage yourselves to help make sure I'm not going crazy, haha. 

It seems like Java might be allotting memory pretty frequently for the engine, even when nothing's going on...? Like, the memory usage climbs very slowly. Pausing the scene slows this down considerably, but I don't know if it stops altogether; I'll test it out some more at some point.

Anyway, PR submitted for just those couple of changes.

**Comment by SolarLune** [comment]
Updated PR based on @rafcolson's suggestion.

**Comment by GoranM** [comment]
> I mean, it keeps growing until a certain point, and then stops; if it were a genuine leak, then that wouldn't happen, right?

I think that's right.

The libraries that we leverage (jbullet and libgdx, primarily) have their own allocation/deallocation patterns, and then the JRE has its own algorithms that manage those at a lower level, so unless you see unceasing, significant jumps in memory consumption, it's probably fine.

**Comment by SolarLune** [comment]
Yeah, I think that makes sense.

I'll close this now. We can re-open it if an actual memory leak that Java isn't taking care of appears.
